#!/bin/bash

## This script allows Nginx server users to quickly and easily create new
## accounts. It takes in a username of your choice and the domain name that
## account will host. Script verifies that the username is valid and then
## takes care of creating the account, setting proper permissions and
## ownership of files and folders and uses a pre-made template to get
## Nginx set up as well.

set -euo pipefail

USERNAME=$1
DOMAIN="$2"

grep -q $USERNAME /etc/passwd && echo "Username already in use" && exit 1

if [[ -z "$USERNAME" ]] || [[ -z "$DOMAIN" ]]
then
  echo -e "\nUsage:\n\ncreate_user <username> <domain name>\n"
  echo "Please try and keep the username 10 characters or less."
  echo -e "Do not include the <> around the username or domain.\n"
  exit 1
fi

useradd -m $USERNAME
usermod -aG $USERNAME nginx
chmod 710 /home/$USERNAME
mkdir /home/$USERNAME/public_html
chmod 750 /home/$USERNAME/public_html
chown -R $USERNAME:$USERNAME /home/$USERNAME
cp /etc/nginx/conf.d/.default_template /etc/nginx/conf.d/$USERNAME.conf
sed -i -e "s/USERNAME/$USERNAME/" -e "s/DOMAIN_NAME1/$DOMAIN/" -e "s/DOMAIN_NAME2/www\.$DOMAIN/" /etc/nginx/conf.d/$USERNAME.conf
systemctl restart nginx

echo "$USERNAME has been added"
